- name: Install stow
  become: false
  homebrew:
    name: stow
    state: present
  tags:
    - mac_os_dotfiles
    - mac_os

- name: Install stow
  apt:
    name: stow
    state: present
  tags:
    - debian_linux_dotfiles
    - debian_linux

- name: Clone .dotfiles repo
  ansible.builtin.git:
    repo: "https://github.com/arthur-yatsun/.dotfiles.git"
    dest: "~/documents/repos/.dotfiles"
    clone: yes
    update: yes
    recursive: yes
  tags:
    - mac_os_dotfiles
    - debian_linux_dotfiles
    - mac_os
    - debian_linux

- name: Install .dotfiles
  shell: "cd ~/documents/repos/.dotfiles && ./install.sh"
  tags:
    - mac_os_dotfiles
    - debian_linux_dotfiles
    - mac_os
    - debian_linux

- name: Make .dotfiles/bin/.local/scripts executable
  file:
    path: "~/.dotfiles/bin/.local/scripts"
    mode: 0755
    recurse: yes
  tags:
    - mac_os_dotfiles
    - debian_linux_dotfiles
    - mac_os
    - debian_linux